"""
Tool: report_tool.py
=====================

Custom Python tool used exclusively by Agent 4 (RecommendationReportAgent).

Responsibilities:
    - Build a rich human-readable Markdown report from scored meals
    - Save the Markdown report to disk with a timestamped filename
    - Save a structured JSON results file to disk
    - Print a formatted console summary for the user

All functions are pure or have clearly bounded side-effects (file I/O).
No LLM calls are made in this tool.

Assignment compliance:
    ✔  Custom Python tool (not an LLM call)
    ✔  Strict type hinting on all public functions
    ✔  Descriptive docstrings with Args / Returns / Raises
    ✔  Robust error handling (IOError, permission, directory creation)
    ✔  Saves outputs locally — no cloud or paid API dependency
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Any, Dict, List, Optional

# ─────────────────────────────────────────────────────────────
# Output directory constants
# ─────────────────────────────────────────────────────────────
# REPORTS_DIR: str = "outputs/reports"
# RESULTS_DIR: str = "outputs/results"
PROJECT_ROOT: str = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

REPORTS_DIR: str = os.path.join(PROJECT_ROOT, "outputs", "reports")
RESULTS_DIR: str = os.path.join(PROJECT_ROOT, "outputs", "results")

# ═════════════════════════════════════════════════════════════
# Public API
# ═════════════════════════════════════════════════════════════

def build_markdown_report(
    meals: List[Dict[str, Any]],
    preferences: Dict[str, Any],
) -> str:
    """
    Build a rich Markdown report summarising the top meal recommendations.

    The report includes:
        - Header with generation timestamp
        - User preferences summary
        - One detailed "meal card" per recommendation
        - Score comparison table across all recommendations
        - Aggregate statistics (avg calories, avg protein, avg score)

    Args:
        meals: Enriched list of meal dicts (each has ``rank``, ``badge``,
               ``final_score``, ``category``, ``reason``, and nutrition fields).
        preferences: User preference dict from Agent 1 (diet, calorie_limit,
                     exclude, cuisine).

    Returns:
        A single Markdown string ready to be written to a .md file.

    Raises:
        TypeError: If ``meals`` is not a list or ``preferences`` is not a dict.

    Example:
        >>> md = build_markdown_report(enriched_meals, {"diet": "vegan"})
        >>> md.startswith("# 🍽️")
        True
    """
    if not isinstance(meals, list):
        raise TypeError(f"meals must be a list, got {type(meals).__name__}")
    if not isinstance(preferences, dict):
        raise TypeError(f"preferences must be a dict, got {type(preferences).__name__}")

    now: str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines: List[str] = []

    # ── Header ────────────────────────────────────────────────
    lines += [
        "# 🍽️  Food Recommendation Report",
        f"> **Generated:** {now}  |  **Top N:** {len(meals)}",
        "",
        "---",
        "",
    ]

    # ── User Preferences Summary ───────────────────────────────
    lines += _build_preferences_section(preferences)

    if not meals:
        lines += [
            "## ⚠️  No Recommendations",
            "",
            "No meals could be matched against your criteria.",
            "",
            "**Suggestions:**",
            "- Increase your calorie limit",
            "- Remove some exclusions",
            "- Try a less restrictive diet type",
        ]
        return "\n".join(lines)

    # ── Meal Cards ────────────────────────────────────────────
    lines += ["## 🏆 Top Recommendations", ""]
    for meal in meals:
        lines += _build_meal_card(meal)

    # ── Score Comparison Table ────────────────────────────────
    lines += _build_comparison_table(meals)

    # ── Summary Statistics ────────────────────────────────────
    lines += _build_statistics_section(meals)

    # ── Footer ────────────────────────────────────────────────
    lines += [
        "",
        "---",
        "",
        "_Report generated by **Food Recommendation MAS** — Agent 4: Recommendation & Report Agent_",
    ]

    return "\n".join(lines)


def save_markdown_report(
    report_md: str,
    output_dir: Optional[str] = None,
    filename_prefix: str = "report",
) -> str:
    """
    Write a Markdown report string to a timestamped file on disk.

    The output directory is created automatically if it does not exist.

    Args:
        report_md:  The complete Markdown string to write.
        output_dir: Directory to save the report in. If None, uses REPORTS_DIR.

    Returns:
        The absolute path of the saved file.

    Raises:
        TypeError:  If ``report_md`` is not a string.
        IOError:    If the file cannot be written (permissions, disk full, etc.).

    Example:
        >>> path = save_markdown_report("# My Report")
        >>> path.endswith(".md")
        True
    """
    if not isinstance(report_md, str):
        raise TypeError(f"report_md must be a str, got {type(report_md).__name__}")

    if output_dir is None:
        output_dir = REPORTS_DIR

    os.makedirs(output_dir, exist_ok=True)
    # timestamp: str = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    # filepath: str = os.path.join(output_dir, f"report_{timestamp}.md")
    safe_prefix = _safe_filename_prefix(filename_prefix)
    timestamp: str = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    filepath: str = os.path.join(output_dir, f"{safe_prefix}_{timestamp}.md")

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_md)
    except OSError as exc:
        raise IOError(f"Failed to write report to {filepath}: {exc}") from exc

    print(f"[Agent 4] 📄 Report saved → {filepath}")
    return filepath


def save_json_results(
    meals: List[Dict[str, Any]],
    preferences: Dict[str, Any],
    output_dir: Optional[str] = None,
    filename_prefix: str = "results",
) -> str:
    """
    Persist the final recommendations as a structured JSON file.

    The payload includes generation timestamp, the preferences that were
    used, and the full list of enriched meal dicts.

    Args:
        meals:      Enriched list of recommendation dicts.
        preferences: User preference dict from Agent 1.
        output_dir: Directory to save the JSON in. If None, uses RESULTS_DIR.

    Returns:
        The absolute path of the saved JSON file.

    Raises:
        TypeError: If ``meals`` is not a list or ``preferences`` is not a dict.
        IOError:   If the file cannot be written.

    Example:
        >>> path = save_json_results(enriched_meals, {"diet": "vegan"})
        >>> path.endswith(".json")
        True
    """
    if not isinstance(meals, list):
        raise TypeError(f"meals must be a list, got {type(meals).__name__}")
    if not isinstance(preferences, dict):
        raise TypeError(f"preferences must be a dict, got {type(preferences).__name__}")

    if output_dir is None:
        output_dir = RESULTS_DIR

    os.makedirs(output_dir, exist_ok=True)
        # timestamp: str = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        # filepath: str = os.path.join(output_dir, f"results_{timestamp}.json")
    safe_prefix = _safe_filename_prefix(filename_prefix)
    timestamp: str = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    filepath: str = os.path.join(output_dir, f"{safe_prefix}_{timestamp}.json")
    
    payload: Dict[str, Any] = {
        "generated_at": datetime.now().isoformat(),
        "preferences": preferences,
        "total_recommendations": len(meals),
        "recommendations": meals,
    }

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False, default=str)
    except OSError as exc:
        raise IOError(f"Failed to write JSON to {filepath}: {exc}") from exc

    print(f"[Agent 4] 💾 JSON results saved → {filepath}")
    return filepath


def print_console_summary(
    meals: List[Dict[str, Any]],
    preferences: Dict[str, Any],
) -> None:
    """
    Print a formatted, human-readable summary of recommendations to stdout.

    Uses ASCII score bars and emoji badges to make the output scannable.
    This is the live feedback the user sees immediately after the pipeline runs.

    Args:
        meals:       Enriched list of recommendation dicts with rank/badge.
        preferences: User preference dict (used for context header).

    Returns:
        None. Output goes directly to stdout.

    Raises:
        TypeError: If ``meals`` is not a list.
    """
    if not isinstance(meals, list):
        raise TypeError(f"meals must be a list, got {type(meals).__name__}")

    width: int = 62
    print("\n" + "=" * width)
    print("  🍽️   FOOD RECOMMENDATION RESULTS")
    print("=" * width)

    diet: str = str(preferences.get("diet") or "Any diet")
    cal: Any = preferences.get("calorie_limit") or "No limit"
    excl: List[str] = preferences.get("exclude", [])
    excl_str: str = ", ".join(excl) if excl else "None"
    print(f"  Diet : {diet}")
    print(f"  Limit: {cal} kcal  |  Exclude: {excl_str}")
    print("-" * width)

    if not meals:
        print("  ⚠️  No meals matched your criteria.")
        print("  Tip: Relax your dietary constraints and try again.")
        print("=" * width)
        return

    for meal in meals:
        score: float = _safe_float(meal.get("final_score", meal.get("score", 0)))
        bar_filled: int = round(score * 10)
        bar: str = "█" * bar_filled + "░" * (10 - bar_filled)
        cal_val: Any = meal.get("calories", "?")
        prot_val: Any = meal.get("protein", "?")
        flags: List[str] = meal.get("health_flags", [])
        flag_str: str = ("  ⚠️  " + ", ".join(flags)) if flags else ""
        category: str = str(meal.get("category", "")).capitalize()

        print(f"\n  {meal.get('badge', '')}")
        print(f"    {meal.get('name', 'Unknown Meal')}")
        print(f"    Score : {score:.2f}  [{bar}]  |  {category}")
        print(f"    Cal   : {cal_val} kcal  |  Protein: {prot_val} g{flag_str}")
        print(f"    Why   : {meal.get('reason', 'No reason provided.')}")

    print("\n" + "=" * width)


# ─────────────────────────────────────────────────────────────
# Internal helpers
# ─────────────────────────────────────────────────────────────

def _build_preferences_section(preferences: Dict[str, Any]) -> List[str]:
    """Build the Markdown lines for the user preferences section."""
    excl: List[str] = preferences.get("exclude", []) or []
    excl_str: str = ", ".join(excl) if excl else "None"

    lines: List[str] = [
        "## 📋 Your Preferences",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Diet type | `{preferences.get('diet') or 'Any'}` |",
        f"| Calorie limit | `{preferences.get('calorie_limit') or 'No limit'}` kcal |",
        f"| Exclusions / Allergens | `{excl_str}` |",
        f"| Cuisine preference | `{preferences.get('cuisine') or 'Any'}` |",
        "",
        "---",
        "",
    ]
    return lines


def _build_meal_card(meal: Dict[str, Any]) -> List[str]:
    """Build Markdown lines for a single meal recommendation card."""
    name: str = str(meal.get("name", "Unknown Meal"))
    badge: str = str(meal.get("badge", f"#{meal.get('rank', '?')} Recommended"))
    score: float = _safe_float(meal.get("final_score", meal.get("score", 0)))
    nutrition_score: float = _safe_float(meal.get("nutrition_score", 0))
    category: str = str(meal.get("category", "unknown")).capitalize()
    reason: str = str(meal.get("reason", "No reason provided."))
    health_flags: List[str] = meal.get("health_flags", []) or []
    calories: Any = meal.get("calories", "N/A")
    protein: Any = meal.get("protein", "N/A")
    fat: Any = meal.get("fat", "N/A")
    carbs: Any = meal.get("carbs", "N/A")
    cuisine: str = str(meal.get("cuisine", "N/A"))
    diet_type: str = str(meal.get("diet_type", "N/A"))

    bar_filled: int = round(score * 10)
    score_bar: str = "█" * bar_filled + "░" * (10 - bar_filled)

    lines: List[str] = [
        f"### {badge}  —  {name}",
        "",
        f"**Score:** `{score:.2f}` `[{score_bar}]`  "
        f"**Nutrition:** `{nutrition_score:.2f}`  "
        f"**Category:** {category}  "
        f"**Cuisine:** {cuisine}",
        "",
        "#### 🧪 Nutritional Breakdown",
        "",
        "| Calories | Protein | Fat | Carbs |",
        "|:--------:|:-------:|:---:|:-----:|",
        f"| {calories} kcal | {protein} g | {fat} g | {carbs} g |",
        "",
        f"**Diet type:** `{diet_type}`",
        "",
        "#### 💡 Why This Meal Was Recommended",
        "",
        f"> {reason}",
        "",
    ]

    if health_flags:
        flag_display: str = ", ".join(f"`{f}`" for f in health_flags)
        lines += [
            f"⚠️  **Health Flags:** {flag_display}",
            "",
        ]

    lines += ["---", ""]
    return lines


def _build_comparison_table(meals: List[Dict[str, Any]]) -> List[str]:
    """Build the Markdown score comparison table section."""
    lines: List[str] = [
        "## 📊 Score Comparison",
        "",
        "| Rank | Meal | Final Score | Nutrition Score | Category | Health Flags |",
        "|:----:|------|:-----------:|:---------------:|:--------:|:-------------|",
    ]
    for m in meals:
        score: float = _safe_float(m.get("final_score", m.get("score", 0)))
        nutr: float = _safe_float(m.get("nutrition_score", 0))
        flags: str = ", ".join(m.get("health_flags", []) or []) or "None"
        cat: str = str(m.get("category", "?")).capitalize()
        lines.append(
            f"| {m.get('rank', '?')} "
            f"| {m.get('name', '?')} "
            f"| **{score:.2f}** "
            f"| {nutr:.2f} "
            f"| {cat} "
            f"| {flags} |"
        )
    lines += [""]
    return lines


def _build_statistics_section(meals: List[Dict[str, Any]]) -> List[str]:
    """Build the aggregate statistics section."""
    avg_cal: float = _safe_avg([m.get("calories") for m in meals])
    avg_prot: float = _safe_avg([m.get("protein") for m in meals])
    avg_score: float = _safe_avg([m.get("final_score", m.get("score", 0)) for m in meals])
    healthy_count: int = sum(1 for m in meals if str(m.get("category", "")).lower() == "healthy")
    flag_counts: Dict[str, int] = {}
    for m in meals:
        for flag in (m.get("health_flags") or []):
            flag_counts[flag] = flag_counts.get(flag, 0) + 1

    lines: List[str] = [
        "## 📈 Summary Statistics",
        "",
        f"- **Total recommendations returned:** {len(meals)}",
        f"- **Average calories:** {avg_cal:.1f} kcal",
        f"- **Average protein:** {avg_prot:.1f} g",
        f"- **Average final score:** {avg_score:.2f}",
        f"- **Meals rated 'healthy':** {healthy_count} / {len(meals)}",
    ]

    if flag_counts:
        flags_str: str = ", ".join(f"{k}: {v}" for k, v in flag_counts.items())
        lines.append(f"- **Health flags detected across results:** {flags_str}")

    lines += [""]
    return lines


def _safe_float(value: Any) -> float:
    """Safely convert any value to float, returning 0.0 on failure."""
    if value is None:
        return 0.0
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def _safe_avg(values: List[Any]) -> float:
    """Return the mean of a list, safely skipping None/non-numeric values."""
    valid: List[float] = []
    for v in values:
        try:
            valid.append(float(v))
        except (TypeError, ValueError):
            continue
    return sum(valid) / len(valid) if valid else 0.0

def _safe_filename_prefix(prefix: str) -> str:
    """
    Convert a filename prefix into a safe local filename component.

    Args:
        prefix: Raw filename prefix.

    Returns:
        Safe filename prefix containing only letters, numbers, underscore, or dash.
    """
    cleaned = "".join(
        ch for ch in prefix.strip().replace(" ", "_")
        if ch.isalnum() or ch in ("_", "-")
    )
    return cleaned or "recommendation"